import { Inter } from "next/font/google";
import "./globals.scss";
import Bootstrap from "@/components/Bootstrap";
// import Bootstrap from '../components/Bootstrap'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Bootstrap />

        {children}
      </body>

    </html>
  );
}
